# Generated by Django 4.1.1 on 2022-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
