# Generated by Django 4.1.1 on 2022-09-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partner',
        ),
    ]
